# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.CharField(default='', max_length=255),
        ),
    ]
